databases:
  - name: Motivational Words_DB
    databaseName: motivational words_db
    user: Motivational words
    region: singapore

services:
  - type: web
    name: Motivational words
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Motivational Words_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
